### ISSUE TITLE
Consider letting mapDispatchToConfig be an object or a function.

### ISSUE THREAD

**Issue by mthadley** [metal/metal-redux#3]
This would let you call connect like this:

```js
import {someActionCreator} from '../actons';

export default connect(
	(state, ownConfig) => (
		{
			thing: getThing(ownConfig.id)
		}
	),
	{
		someActionCreator
	}
)(MyComponent);
```

And then `someActionCreator` would be available in `MyComponent`'s config, automatically bound and ready to go. See the `react-redux` documentation on this behavior [here](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options).

**Comment by mthadley** [comment]
P.S. I'm totally willing to a send a PR for this if it would be helpful.

**Comment by mairatma** [comment]
I see, I agree that it makes sense to do this, so we can follow react-redux's api. It would be great if you could send a pr for this :)
